packages:
  - "toolkit/**"
  # - "toolkit/dweb-offscreen-web-canvas-assets"
  # - "toolkit/dweb-core"
  # - "toolkit/dweb-desk-assets"
  # - "toolkit/dweb-profile"
  # - "toolkit/dweb-polyfill"
  # - "toolkit/plaoc/**"
