# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'BFExplorer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftyJSON'
  pod 'SVGKit'
  pod 'SDWebImage'
  pod 'SnapKit'
  pod 'UIColor_Hex_Swift'
  pod 'RxSwift'
  pod 'Moya'
  pod 'SSZipArchive'
  pod 'SDWebImage'
  pod 'SwiftSoup'
  pod 'Toast-Swift'
  pod 'ZLPhotoBrowser'
  pod 'SnapKit'
  pod 'EmptyDataSet-Swift'
  pod 'SwiftSoup'
  pod 'SwiftyTimer'
  
  # https://github.com/hirotakan/MessagePacker
  pod 'MessagePacker'

  # Pods for BFExplorer

#  target 'BFExplorerTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'BFExplorerUITests' do
#    # Pods for testing
#  end

end
