export interface ImpactOptions {
  /**
   * Impact Feedback Style
   *
   * The mass of the objects in the collision simulated by a [UIImpactFeedbackGenerator](https://developer.apple.com/documentation/uikit/uiimpactfeedbackstyle) object.
   *
   * @default ImpactStyle.Heavy
   * @since 1.0.0
   */
  style: ImpactStyle;
}

export enum ImpactStyle {
  /**
   * 大而重的用户界面元素之间的碰撞
   *
   * @since 1.0.0
   */
  Heavy = "HEAVY",

  /**
   * 中等大小的用户界面元素之间的冲突
   *
   * @since 1.0.0
   */
  Medium = "MEDIUM",

  /**
   * 小而轻的用户界面元素之间的碰撞
   *
   * @since 1.0.0
   */
  Light = "LIGHT",
}

export interface NotificationOptions {
  /**
   * 通知反馈类型
   *
   * The type of notification feedback generated by a [UINotificationFeedbackGenerator](https://developer.apple.com/documentation/uikit/uinotificationfeedbacktype) object.
   *
   * @default NotificationType.SUCCESS
   * @since 1.0.0
   */
  type: NotificationType;
}

export enum NotificationType {
  /**
   * 表示任务已成功完成的通知反馈类型
   *
   * @since 1.0.0
   */
  Success = "SUCCESS",

  /**
   * 指示任务已产生警告的通知反馈类型
   *
   * @since 1.0.0
   */
  Warning = "WARNING",

  /**
   * 任务失败的通知反馈类型
   *
   * @since 1.0.0
   */
  Error = "ERROR",
}

export interface VibrateOptions {
  /**
   * 振动持续时间（以毫秒为单位）。
   *
   * @default 300
   * @since 1.0.0
   */
  duration: number;
}

/**
 * @deprecated Use `ImpactOptions`.
 * @since 1.0.0
 */
export type HapticsImpactOptions = ImpactOptions;

/**
 * @deprecated Use `NotificationOptions`.
 * @since 1.0.0
 */
export type HapticsNotificationOptions = NotificationOptions;

/**
 * @deprecated Use `NotificationType`.
 * @since 1.0.0
 */
export const HapticsNotificationType = NotificationType;

/**
 * @deprecated Use `ImpactStyle`.
 * @since 1.0.0
 */
export const HapticsImpactStyle = ImpactStyle;
