// Generated by Karakum - do not modify it manually!

package org.node.buffer

import org.node.array.ReadonlyArray


sealed external interface BufferToJSONResult {
    var type: String /* 'Buffer' */
    var data: ReadonlyArray<JsNumber>
}
