// Generated by Karakum - do not modify it manually!

@file:JsModule("node:buffer")

package org.node.buffer

import org.khronos.webgl.ArrayBuffer


external fun isAscii(input: Buffer): Boolean

external fun isAscii(input: ArrayBuffer): Boolean

