// Generated by Karakum - do not modify it manually!

@file:JsModule("node:buffer")

package org.node.buffer

import org.w3c.files.Blob


/**
 * Resolves a `'blob:nodedata:...'` an associated `Blob` object registered using
 * a prior call to `URL.createObjectURL()`.
 * @since v16.7.0
 * @experimental
 * @param id A `'blob:nodedata:...` URL string returned by a prior call to `URL.createObjectURL()`.
 */
external fun resolveObjectURL(id: String): Blob?
