// Generated by Karakum - do not modify it manually!


package org.node.buffer


typealias WithImplicitCoercion<
    @Suppress("UNUSED_TYPEALIAS_PARAMETER")
    T,
    > = JsAny /* T | {
    valueOf(): T;
} */
